version: '3.8'

services:
  app:
    build: ./Backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    # volumes:
    #   - ./Backend:/app
    # depends_on was removed
    networks:
      - uploader-net

# Defines the network that our services will use to communicate
networks:
  uploader-net:
    driver: bridge